# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Robert Tucker
tagline:          'A collection of minutia'
description:      'A collection of minutia'
url:              https://robertwtucker.com
baseurl:          /

author:
  name:           'Robert Tucker'
  url:            https://twitter.com/robertwtucker

paginate:         3

github:
  repo:           https://github.com/robertwtucker/

gems:
  - jekyll-paginate
  - jekyll-gist
